site_name: My MkDocs-Material Static Website
site_description: MkDocs / Material for MkDocs Example
site_url: https://bristol-glaciology.github.io/example-mkdocs-website/
repo_url: https://github.com/bristol-glaciology/example-mkdocs-website
repo_name: "example-mkdocs-website"

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Source Sans 3
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections

copyright: >
  &copy; Bristol Glaciology Centre —
  <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bristol-glaciology
      name: Bristol Glaciology Centre on GitHub
    - icon: fontawesome/solid/globe
      link: https://bristol-glaciology.github.io
      name: Bristol Glaciology Centre website

nav:
  - Home: index.md
  - Content:
    - Content & Markdown: pages/content.md
    - Jupyter Notebook: pages/notebook.ipynb

plugins:
- mkdocs-jupyter:
    execute: false
    include_source: True
    custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js